<?php
/**
 * 包名：MiotOauth
 * 创建时间：2019.6.28
 * 创建者博客： http://blog.csdn.net/xh870189248
 * 创建者GitHub： https://github.com/xuhongv
 * 创建者：徐宏
 * 描述： 米家授权界面
 */

namespace app\api\controller\oauth;



class MiotOauth extends BaseController
{

    private $server;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $dsn = 'mysql:dbname=' . config('database')['database'] . ';host=' . config('database')['hostname'];;
        $username = config('database')['username'];
        $password = config('database')['password'];

        \OAuth2\Autoloader::register();

        // 获取mysql数据库
        $storage = new \OAuth2\Storage\Pdo(array('dsn' => $dsn, 'username' => $username, 'password' => $password));

        // 实例化一个oauth2.0服务器
        $this->server = new \OAuth2\Server($storage);

        // Add the "Client Credentials" grant type (it is the simplest of the grant types)
        $this->server->addGrantType(new \OAuth2\GrantType\ClientCredentials($storage));

        // Add the "Authorization Code" grant type (this is where the oauth magic happens)
        $this->server->addGrantType(new \OAuth2\GrantType\AuthorizationCode($storage));

    }

    //https://www.xuhonys.cn/oauth/aligenie?response_type=code&client_id=xuhong&state=xyz
    public function authorize()
    {

        $request = \OAuth2\Request::createFromGlobals();
        $response = new \OAuth2\Response();

        // 校验同步请求是否有效
        if (!$this->server->validateAuthorizeRequest($request, $response)) {
            //回调给客户端
            return utilsResponse($response->getStatusCode(), 'sorry , fail!', $response->getParameters(), 200);
        }

        // 显示一个授权界面，即为要求用户输入账号密码
        if (empty($_POST)) {
            exit($this->fetch());
        }

        //登录操作
        if (request()->isPost()) {
            $getPostDataArry = input('post.');

            //从数据库查询 username
            try {
                $user = model('WcUserCode')->get(['active' => 0, 'code' => $getPostDataArry['username']]);
            } catch (\Exception $exception) {
                return utilsResponse(-1, '用户查询报错:' . $exception->getMessage(), [], 400);
            }

            //return utilsResponse(-1, '用户查询报错:' . json_encode($user), [], 400);
            if (!$user) {
                $this->error("用户不存在！");
            }

            //对比失效时间
            if (time() > $user['expire']) {
                $this->error("授权码失效，请重新获取！");
            }

            try {
                $saveUser = model('WcUserCode')->save(['active' => 1, 'code' => ''], ['user_id' => $user['user_id']]);
            } catch (\Exception $exception) {
                return utilsResponse(-1, '用户保存报错:' . $exception->getMessage(), [], 400);
            }

            if (!$saveUser) {
                $this->error("授权失败，请联系管理员！001");
            }

        } else {
            return utilsResponse(-1, 'request is not post', [], 400);
        }
        //当前的用户 id 打印下
        //utilsSaveLogs("utilsSaveLogs('***********Aligenie to me ---> ".$user['user_id'], 3);
        //同步授权使能
        $is_authorized = true;
        //最后一个参数就是当前的code和$user['id']同时入库
        $this->server->handleAuthorizeRequest($request, $response, $is_authorized, $user['user_id']);
        if ($is_authorized) {
            // this is only here so that you get to see your code in the cURL request. Otherwise, we'd redirect back to the client
            $code = substr($response->getHttpHeader('Location'), strpos($response->getHttpHeader('Location'), 'code=') + 5, 40);
        }
        $response->send();
        return '';
    }
}