<?php
/**
 * Created by PhpStorm.
 * User: xuhongv
 * Date: 2019-02-01
 * Time: 00:44
 */

namespace app\wechat\controller;


use function PHPSTORM_META\type;

class GuideDeviceTypeListActivity extends BaseWeChat
{


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //如果未登陆，返回绑定界面授权
        if (!$this->isLogin()) {
            return $this->redirect('BindPhoneActivity/index');
        }
    }


    public function index()
    {
        //var_dump($this->mWeiChatOptions);

        $data = json_encode($this->devicesList);
        $this->assign('list', $data);
        return $this->fetch('', ['devicesList' => $this->devicesList]);
    }


}