<?php
/**
 * Created by PhpStorm.
 * User: xuhongv
 * Date: 2019-02-01
 * Time: 19:21
 */

namespace app\wechat\controller;


use app\api\controller\wechat\Device;
use think\debug\Console;

class ReadyDeviceActivity extends BaseWeChat
{


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //如果未登陆，返回绑定界面授权
        if (!$this->isLogin()) {
            return $this->redirect('BindPhoneActivity/index');
        }
    }


    public function index()
    {

        $index = input('get.');

        //严格判断
        if (!is_array($index))
            return '';
        if (!isset($index['index']))
            return '';

        //取得配网信息
        $netMessage = ($this->devicesList)[$index['index']]['actionNet'];
        $actionNetPic = ($this->devicesList)[$index['index']]['actionNetPic'];

//        utilsSaveLogs('get net $index[\'index\']:' . $index['index']);
//        utilsSaveLogs('get net message:' . $netMessage);

        try {
            // 实例接口
            $wechat = new \WeChat\Script($this->mWeiChatOptions);
            // 执行操作
            $result = $wechat->getJsSign($this->mWeiChatOptions['weichatDomain'] . '/wechat/ready_device_activity/index.html?index=' . $index['index']);
        } catch (Exception $e) {
            // 异常处理
            utilsSaveLogs('get error message:' .  $e->getMessage());
            // echo $e->getMessage();
        }

        //重新设置需要调的jsApi
        unset($result['jsApiList']);
        $result['jsApiList'] = [
            'openWXDeviceLib', 'startScanWXDevice', 'onScanWXDeviceResult', 'configWXDeviceWiFi', 'hideMenuItems'
        ];


        $data = json_encode([
            'icon' => $actionNetPic,
            'message' => $netMessage,
            'wechat' => $result,
            'user' => $this->localUser,
        ]);

        $this->assign('deviceInfo', $data);
        return $this->fetch();
    }


    public function bindDevice(){

        if (!$this->request->isPost()) {
            return '';
        }
        $postData = input('post.');

        //跨控制器访问
        $model2 = new Device();
        return $model2->bindDevice($postData);
    }


    public function getUserDeviceList(){

        if (!$this->request->isPost()) {
            return '';
        }
        $postData = input('post.');

        //跨控制器访问
        $model2 = new Device();
        return $model2->getUserBindDevices($postData);
    }




}